// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrTzp7iSggnEY-y7CWEQFKdLlY74iwEIY',
    appId: '1:70040548260:android:04b12c08d2e25fa90c0731',
    messagingSenderId: '70040548260',
    projectId: 'mynotes-flutter-tvuksan',
    storageBucket: 'mynotes-flutter-tvuksan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7LNzicrkK2yEa1qa-Qe8NTORRuV_NT0o',
    appId: '1:70040548260:ios:3c33f49bf6bc4e5e0c0731',
    messagingSenderId: '70040548260',
    projectId: 'mynotes-flutter-tvuksan',
    storageBucket: 'mynotes-flutter-tvuksan.appspot.com',
    iosClientId: '70040548260-0ja9nbco6opok0ajdmps51oanv7o82v4.apps.googleusercontent.com',
    iosBundleId: 'hr.animsenezdravo.mynotes',
  );
}
